spring.application.name=rentacar

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=rentacar
management.metrics.tags.environment=production

info.app.name=RentCar API
info.app.version=1.0.0
info.app.description=Microservicio de arriendo de autos - EP3 DevOps DuocUC